//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class match_user
    {
        public int match_user_id { get; set; }
        public int match_id { get; set; }
        public short user_id { get; set; }
        public bool local { get; set; }
        public Nullable<short> team_id { get; set; }
        public byte score { get; set; }
        public Nullable<byte> yellow_cards { get; set; }
        public Nullable<byte> red_cards { get; set; }
        public bool win { get; set; }
        public bool walk_over { get; set; }
    
        public virtual match match { get; set; }
        public virtual user user { get; set; }
    }
}
