//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public match()
        {
            this.match_user = new HashSet<match_user>();
        }
    
        public int match_id { get; set; }
        public byte tournament_id { get; set; }
        public byte match_type_id { get; set; }
        public bool played { get; set; }
        public Nullable<System.DateTime> date_played { get; set; }
    
        public virtual match_type match_type { get; set; }
        public virtual tournament tournament { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<match_user> match_user { get; set; }
    }
}
