//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_league
    {
        public int team_league_id { get; set; }
        public short team_id { get; set; }
        public byte league_id { get; set; }
    
        public virtual league league { get; set; }
        public virtual team team { get; set; }
    }
}
