//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_user_group
    {
        public int team_user_group_id { get; set; }
        public int user_group_id { get; set; }
        public short team_id { get; set; }
    
        public virtual team team { get; set; }
        public virtual user_group user_group { get; set; }
    }
}
