//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_league
    {
        public int team_league_id { get; set; }
        public short team_id { get; set; }
        public byte league_id { get; set; }
    
        public virtual league league { get; set; }
        public virtual team team { get; set; }
    }
}
