//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class team_user_group
    {
        public int team_user_group_id { get; set; }
        public int user_group_id { get; set; }
        public short team_id { get; set; }
    
        public virtual team team { get; set; }
        public virtual user_group user_group { get; set; }
    }
}
