//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FifaPSL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_auth
    {
        public byte user_auth_id { get; set; }
        public short user_id { get; set; }
        public string token { get; set; }
        public System.DateTime issued { get; set; }
    
        public virtual user user { get; set; }
    }
}
